### PR TITLE
Makefile: set build.code_debug flag to arduino-cli

### PR DESCRIPTION
**Pull request by nor2101**
Testing with debug level 5

### CODE REVIEW

**Comment by gizero** [comment]
Once cleaned up (commits should be squashed into a single one), LGTM... as a first approximation. We'd better allow the `make` caller to be able to control the flag value via a dedicated `Makefile` variable.

**Comment by nor2101** [comment]
> 
> 
> Once cleaned up (commits should be squashed into a single one), LGTM... as a first approximation. We'd better allow the `make` caller to be able to control the flag value via a dedicated `Makefile` variable.
> 
> Commit message should be better phrased as: `Makefile: set build.code_debug flag to arduino-cli` (see previous commits touching `Makefile` to keep a consistent commit message style)

Ok, thanks for the feedback! I was also thinking about being able to control the parameter through an env var similar to secret_salt and server (except not secret). I'll try to come up with something and I'll propose the change

**Comment by nor2101** [comment]
https://github.com/A-A-Milano-Smart-Park/msp-firmware/blob/db522851f4f023be2a16730515cc26068274871b/Makefile#L157

```suggestion
        ifdef CORE_DEBUG_LEVEL
        --build-property 'build.code_debug=CORE_DEBUG_LEVEL' \ 
        else
        --build-property 'build.code_debug=1' \ 
        endif
```

@gizero How about something like this?

**Comment by gizero** [comment]
Bit you Aldo need to handle defaulting the variabile if not explicitly provided by the user to avoid breaking the arduino-cli command line

**Comment by nor2101** [comment]
> 
> 
> But you also need to handle defaulting the variabile if not explicitly provided by the user to avoid breaking the arduino-cli command line

I thought `else` handled defaulting the variable to 1 in case the user did not input DEBUG_LEV as an arg

**Pull request merged**
